
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

 /* Enter a start condition.  This macro really ought to take a parameter,
  * but we do it the disgusting crufty way forced on us by the ()-less
  * definition of BEGIN.
  */
#define BEGIN (yy_start) = 1 + 2 *
  /* Translate the current start state into a value that can be later handed
   * to BEGIN to return to the state.  The YYSTATE alias is for lex
   * compatibility.
   */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
   /* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state* YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE* yyin, * yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

#define YY_LESS_LINENO(n)
#define YY_LINENO_REWIND_TO(ptr)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
{
	FILE* yy_input_file;

	char* yy_ch_buf;		/* input buffer */
	char* yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	int yy_bs_lineno; /**< The line count. */
	int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE* yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
 /* Same as previous macro, but useful when we know that the buffer stack is not
  * NULL or when we need an lvalue. For internal use only.
  */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

  /* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char* yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart(FILE* input_file);
void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer);
YY_BUFFER_STATE yy_create_buffer(FILE* file, int size);
void yy_delete_buffer(YY_BUFFER_STATE b);
void yy_flush_buffer(YY_BUFFER_STATE b);
void yypush_buffer_state(YY_BUFFER_STATE new_buffer);
void yypop_buffer_state(void);

static void yyensure_buffer_stack(void);
static void yy_load_buffer_state(void);
static void yy_init_buffer(YY_BUFFER_STATE b, FILE* file);
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer(char* base, yy_size_t size);
YY_BUFFER_STATE yy_scan_string(const char* yy_str);
YY_BUFFER_STATE yy_scan_bytes(const char* bytes, int len);

void* yyalloc(yy_size_t);
void* yyrealloc(void*, yy_size_t);
void yyfree(void*);

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE* yyin = NULL, * yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char* yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state(void);
static yy_state_type yy_try_NUL_trans(yy_state_type current_state);
static int yy_get_next_buffer(void);
static void yynoreturn yy_fatal_error(const char* msg);

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
 /* This struct is not used in this scanner,
	but its presence is necessary. */
struct yy_trans_info
{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
};
static const flex_int16_t yy_accept[223] =
{ 0,
	0,    0,   66,   66,    0,    0,    0,    0,   78,   77,
   76,   64,   61,   56,   58,   44,   45,   50,   48,   57,
   49,   77,   51,   68,   53,   52,   54,   75,   75,   75,
   75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
   75,   75,   75,   75,   75,   77,   55,   46,   47,   65,
   67,   59,   60,   62,   63,   76,    0,   72,   43,    0,
	0,   36,    0,    0,   68,   39,   40,   71,   37,   71,
   68,    0,   68,    0,   33,   34,   32,    0,   75,   75,
	2,   75,   75,   75,   75,   75,    7,   75,   75,   75,
   75,   75,   75,    9,   75,   75,   75,   75,   75,   26,

   75,   75,   75,   75,   75,   75,   75,   75,   75,   38,
   35,   65,   59,   60,   62,   70,   69,    0,   71,    0,
   71,   42,   41,   27,   75,   75,   75,   75,    6,   75,
   75,   12,   75,   13,   75,   75,   75,   75,   75,   75,
   29,   75,   75,   75,   75,   75,   23,   75,   75,   75,
   28,   70,    0,   69,    0,    0,   68,   75,   75,    4,
   75,   75,   10,   75,   75,   75,   75,   75,   31,   75,
   75,   75,   75,   75,   75,   24,   73,   75,   70,   70,
   69,   69,   75,   30,    5,   75,   75,   74,   75,   75,
   75,   75,   75,   75,   75,   75,   75,   75,   25,   75,

	8,   11,   14,   75,   75,   75,   17,   75,   75,   20,
   21,   22,    3,   75,    1,   16,   18,   75,   15,   75,
   19,    0
};

static const YY_CHAR yy_ec[256] =
{ 0,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    3,    4,    1,    1,    5,    6,    7,
	8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
   15,   15,   15,   15,   15,   15,   15,    1,    1,   16,
   17,   18,    1,    1,   19,   20,   21,   22,   23,   24,
   25,   26,   27,   28,   28,   29,   30,   31,   32,   33,
   28,   34,   35,   36,   37,   38,   39,   40,   41,   28,
	1,   42,    1,   43,   44,    1,   45,   46,   47,   48,

   49,   50,   51,   52,   53,   28,   28,   54,   55,   56,
   57,   58,   28,   59,   60,   61,   62,   63,   64,   65,
   66,   28,   67,    1,   68,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1
};

static const YY_CHAR yy_meta[69] =
{ 0,
	1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    5,    1,    1,    1,    5,    5,
	5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
	5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
	5,    1,    1,    5,    5,    5,    5,    5,    5,    5,
	5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
	5,    5,    5,    5,    5,    5,    1,    1
};

static const flex_int16_t yy_base[231] =
{ 0,
	0,    0,  438,  437,  437,  435,   67,   68,  435,  442,
  428,  423,  442,   56,  442,  442,  442,  385,   70,  442,
   73,  386,  383,   66,   75,  442,   77,   49,   65,   79,
   72,   72,   98,    0,   83,   64,   80,   84,   85,   86,
   51,  117,  116,  101,  102,  382,  381,  442,  442,    0,
  442,    0,  391,    0,  442,  389,  387,  442,  442,  373,
  372,  442,  126,  371,  148,  442,  442,  141,  442,  147,
  154,  170,  103,  364,  442,  442,  442,  363,    0,  136,
	0,  117,  113,  146,  152,  156,  150,  153,  143,  160,
  159,  146,  163,    0,  162,  164,  169,  180,  168,    0,

  178,  187,  173,  186,  196,  194,  184,  195,  190,  442,
  442,    0,    0,  348,    0,  208,  212,  226,  222,  215,
  302,  442,  442,    0,  203,  220,  221,  212,    0,  230,
  228,    0,  218,    0,  231,  234,  226,  237,  229,  226,
	0,  226,  230,  238,  231,  246,    0,  242,  251,  250,
	0,  246,  267,  269,  270,  294,  279,  252,  267,    0,
  261,  270,  275,  280,  274,  270,  273,  283,    0,  281,
  293,  292,  289,  284,  298,    0,    0,  297,  310,  311,
  312,  318,  318,    0,    0,  316,  316,    0,  322,  320,
  300,  325,  326,  315,  331,  332,  326,  322,    0,  328,

	0,    0,    0,  328,  329,  333,    0,  345,  335,    0,
	0,    0,    0,  341,    0,    0,    0,  346,    0,  355,
	0,  442,  403,  408,  413,  418,   72,  423,  428,  433
};

static const flex_int16_t yy_def[231] =
{ 0,
  222,    1,  223,  223,  224,  224,  225,  225,  222,  222,
  222,  226,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  227,  227,  227,
  227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
  227,  227,  227,  227,  227,  222,  222,  222,  222,  228,
  222,  229,  222,  230,  222,  222,  226,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  227,  227,
  227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
  227,  227,  227,  227,  227,  227,  227,  227,  227,  227,

  227,  227,  227,  227,  227,  227,  227,  227,  227,  222,
  222,  228,  229,  222,  230,  222,  222,  222,  222,  222,
  222,  222,  222,  227,  227,  227,  227,  227,  227,  227,
  227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
  227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
  227,  222,  222,  222,  222,  222,  222,  227,  227,  227,
  227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
  227,  227,  227,  227,  227,  227,  227,  227,  222,  222,
  222,  222,  227,  227,  227,  227,  227,  227,  227,  227,
  227,  227,  227,  227,  227,  227,  227,  227,  227,  227,

  227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
  227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
  227,    0,  222,  222,  222,  222,  222,  222,  222,  222
};

static const flex_int16_t yy_nxt[511] =
{ 0,
   10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
   20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
   30,   31,   32,   33,   34,   34,   35,   34,   36,   37,
   38,   39,   40,   41,   42,   43,   34,   34,   44,   45,
   34,   46,   47,   34,   28,   29,   30,   31,   32,   33,
   34,   34,   35,   36,   37,   38,   39,   40,   41,   42,
   43,   34,   34,   44,   45,   34,   48,   49,   10,   10,
   55,   55,   59,  103,   63,   60,   79,   63,   70,   80,
   71,   61,   64,   81,   65,   64,   66,   65,   72,   67,
   74,   75,   76,   77,   78,   97,   82,   84,   86,  103,

   88,   60,   89,   87,   80,   83,   94,   61,   81,   73,
   85,   98,   95,   96,   72,   99,   90,   73,  100,  101,
   97,   82,  102,   84,   86,   88,  108,   89,   87,   91,
   83,   92,   94,  109,   93,   85,   98,   95,   96,  104,
   99,  106,   90,  100,  101,   60,   73,  102,  125,  107,
  126,   61,  108,  105,   91,   68,   92,  124,  109,   93,
   70,  119,   71,  118,  132,  104,   70,  106,   71,  118,
   72,   60,  135,  125,  107,  126,  118,   61,  105,  120,
  127,  120,  128,  124,  121,  129,  130,  131,  133,  118,
  132,   73,  134,  136,  137,  118,   72,   73,  135,  138,

  139,  140,  118,  141,  142,  127,  144,  128,  145,  143,
  129,  130,  131,  133,  146,  147,  148,  134,  136,  137,
  149,  150,  152,  151,  138,  139,  154,  140,  141,  157,
  142,  158,  144,  145,  143,  156,  119,  156,  159,  146,
  121,  147,  148,  160,  118,  149,  161,  150,  151,  162,
  163,  153,  164,  165,  166,  155,  158,  167,   73,  168,
  179,  169,  170,  171,  159,  172,  173,  174,  175,  160,
  118,  161,  176,  177,  183,  162,  163,  164,  178,  165,
  166,  180,  167,  181,  182,  168,  169,  170,  171,  153,
  172,  173,  174,  157,  175,  184,  185,  176,  186,  177,

  183,  187,  188,  178,  189,  190,  191,  192,  121,  193,
  153,  194,  155,  155,  195,  196,  121,  197,  198,  199,
  184,  185,   73,  186,  179,  180,  181,  187,  188,  189,
  190,  191,  182,  192,  193,  205,  200,  194,  201,  202,
  195,  196,  197,  203,  198,  199,  204,  206,  207,  114,
  208,  209,  210,  153,  153,  155,  211,  212,  213,  214,
  205,  155,  200,  215,  201,  202,  216,  217,  220,  203,
  218,  219,  204,  206,  207,  208,  221,  209,  210,  123,
  122,  211,  212,  213,  214,   68,  117,  116,  215,   58,
   56,  216,  114,  217,  220,  218,  219,  111,  110,   69,

   68,   62,  221,   50,   50,   50,   50,   50,   52,   52,
   52,   52,   52,   54,   54,   54,   54,   54,   57,   57,
   57,   57,   57,  112,  112,   58,  112,  112,  113,   56,
  113,  113,  113,  115,  222,  115,   53,  115,   53,   51,
   51,    9,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  222,  222,

  222,  222,  222,  222,  222,  222,  222,  222,  222,  222
};

static const flex_int16_t yy_chk[511] =
{ 0,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
	1,    1,    1,    1,    1,    1,    1,    1,    7,    8,
	7,    8,   14,   41,   19,   14,  227,   21,   24,   28,
   24,   14,   19,   28,   19,   21,   19,   21,   24,   21,
   25,   25,   25,   27,   27,   36,   29,   30,   31,   41,

   32,   14,   32,   31,   28,   29,   35,   14,   28,   24,
   30,   37,   35,   35,   24,   38,   33,   73,   39,   40,
   36,   29,   40,   30,   31,   32,   44,   32,   31,   33,
   29,   33,   35,   45,   33,   30,   37,   35,   35,   42,
   38,   43,   33,   39,   40,   63,   73,   40,   82,   43,
   83,   63,   44,   42,   33,   68,   33,   80,   45,   33,
   65,   70,   65,   68,   89,   42,   71,   43,   71,   70,
   65,   63,   92,   82,   43,   83,   71,   63,   42,   72,
   84,   72,   85,   80,   72,   86,   87,   88,   90,   68,
   89,   65,   91,   93,   95,   70,   65,   71,   92,   96,

   97,   98,   71,   99,  101,   84,  102,   85,  103,  101,
   86,   87,   88,   90,  104,  105,  106,   91,   93,   95,
  107,  108,  116,  109,   96,   97,  117,   98,   99,  120,
  101,  125,  102,  103,  101,  118,  119,  118,  126,  104,
  118,  105,  106,  127,  119,  107,  128,  108,  109,  130,
  131,  116,  133,  135,  136,  117,  125,  137,  120,  138,
  152,  139,  140,  142,  126,  143,  144,  145,  146,  127,
  119,  128,  148,  149,  158,  130,  131,  133,  150,  135,
  136,  153,  137,  154,  155,  138,  139,  140,  142,  152,
  143,  144,  145,  157,  146,  159,  161,  148,  162,  149,

  158,  163,  164,  150,  165,  166,  167,  168,  156,  170,
  153,  171,  154,  155,  172,  173,  121,  174,  175,  178,
  159,  161,  157,  162,  179,  180,  181,  163,  164,  165,
  166,  167,  182,  168,  170,  191,  183,  171,  186,  187,
  172,  173,  174,  189,  175,  178,  190,  192,  193,  114,
  194,  195,  196,  179,  180,  181,  197,  198,  200,  204,
  191,  182,  183,  205,  186,  187,  206,  208,  218,  189,
  209,  214,  190,  192,  193,  194,  220,  195,  196,   78,
   74,  197,  198,  200,  204,   64,   61,   60,  205,   57,
   56,  206,   53,  208,  218,  209,  214,   47,   46,   23,

   22,   18,  220,  223,  223,  223,  223,  223,  224,  224,
  224,  224,  224,  225,  225,  225,  225,  225,  226,  226,
  226,  226,  226,  228,  228,   12,  228,  228,  229,   11,
  229,  229,  229,  230,    9,  230,    6,  230,    5,    4,
	3,  222,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
  222,  222,  222,  222,  222,  222,  222,  222,  222,  222,

  222,  222,  222,  222,  222,  222,  222,  222,  222,  222
};

static yy_state_type yy_last_accepting_state;
static char* yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char* yytext;
#line 1 "flexample.l"
#define YY_NO_UNISTD_H 1
#line 6 "flexample.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../parser/parser.tab.h"

#pragma warning(disable : 4996)
#define YY_DECL int yylex()

int val(char c);
void remove_substr(char* str, const char* substr);
int HextoDeci(char* str);
int BintoDeci(char* str);

int result = 0;

#line 648 "lex.yy.c"

#line 650 "lex.yy.c"

#define INITIAL 0
#define STRING_LITERAL 1
#define COMMENT 2
#define DATETIME 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals(void);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy(void);

int yyget_debug(void);

void yyset_debug(int debug_flag);

YY_EXTRA_TYPE yyget_extra(void);

void yyset_extra(YY_EXTRA_TYPE user_defined);

FILE* yyget_in(void);

void yyset_in(FILE* _in_str);

FILE* yyget_out(void);

void yyset_out(FILE* _out_str);

int yyget_leng(void);

char* yyget_text(void);

int yyget_lineno(void);

void yyset_lineno(int _line_number);

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap(void);
#else
extern int yywrap(void);
#endif
#endif

#ifndef YY_NO_UNPUT

static void yyunput(int c, char* buf_ptr);

#endif

#ifndef yytext_ptr
static void yy_flex_strncpy(char*, const char*, int);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(const char*);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput(void);
#else
static int input(void);
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

 /* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
  * is returned in "result".
  */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

  /* No semi-colon after return; correct usage is to write "yyterminate();" -
   * we don't want an extra ';' after the "return" because that will cause
   * some compilers to complain about unreachable statements.
   */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

   /* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex(void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

 /* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char* yy_cp,* yy_bp;
	int yy_act;

	if (!(yy_init))
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if (!(yy_start))
			(yy_start) = 1;	/* first start state */

		if (!yyin)
			yyin = stdin;

		if (!yyout)
			yyout = stdout;

		if (!YY_CURRENT_BUFFER) {
			yyensure_buffer_stack();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin, YY_BUF_SIZE);
		}

		yy_load_buffer_state();
		}

	{
#line 27 "flexample.l"


#line 30 "flexample.l"
	char buf[100000];
	memset(buf, '\0', 100000);


#line 878 "lex.yy.c"

	while ( /*CONSTCOND*/1)		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if (yy_accept[yy_current_state])
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
				{
				yy_current_state = (int)yy_def[yy_current_state];
				if (yy_current_state >= 223)
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			} while (yy_base[yy_current_state] != 442);

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if (yy_act == 0)
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch (yy_act)
	{ /* beginning of action switch */
			case 0: /* must back up */
				/* undo the effects of YY_DO_BEFORE_ACTION */
				*yy_cp = (yy_hold_char);
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;

	case 1:
	YY_RULE_SETUP
	#line 34 "flexample.l"
	{return IMPORTS; }
		YY_BREAK
	case 2:
	YY_RULE_SETUP
	#line 35 "flexample.l"
	{return AS; }
		YY_BREAK
	case 3:
	YY_RULE_SETUP
	#line 36 "flexample.l"
	{return BOOLEAN; }
		YY_BREAK
	case 4:
	YY_RULE_SETUP
	#line 37 "flexample.l"
	{return CASE; }
		YY_BREAK
	case 5:
	YY_RULE_SETUP
	#line 38 "flexample.l"
	{return CONST; }
		YY_BREAK
	case 6:
	YY_RULE_SETUP
	#line 39 "flexample.l"
	{return DIM; }
		YY_BREAK
	case 7:
	YY_RULE_SETUP
	#line 40 "flexample.l"
	{return DO; }
		YY_BREAK
	case 8:
	YY_RULE_SETUP
	#line 41 "flexample.l"
	{return DOUBLE; }
		YY_BREAK
	case 9:
	YY_RULE_SETUP
	#line 42 "flexample.l"
	{return IF; }
		YY_BREAK
	case 10:
	YY_RULE_SETUP
	#line 43 "flexample.l"
	{return ELSE; }
		YY_BREAK
	case 11:
	YY_RULE_SETUP
	#line 44 "flexample.l"
	{return ELSEIF; }
		YY_BREAK
	case 12:
	YY_RULE_SETUP
	#line 45 "flexample.l"
	{return END; }
		YY_BREAK
	case 13:
	YY_RULE_SETUP
	#line 46 "flexample.l"
	{return FOR; }
		YY_BREAK
	case 14:
	YY_RULE_SETUP
	#line 47 "flexample.l"
	{return FRIEND; }
		YY_BREAK
	case 15:
	YY_RULE_SETUP
	#line 48 "flexample.l"
	{return FUNCTION; }
		YY_BREAK
	case 16:
	YY_RULE_SETUP
	#line 49 "flexample.l"
	{return INT; }
		YY_BREAK
	case 17:
	YY_RULE_SETUP
	#line 50 "flexample.l"
	{return MODULE; }
		YY_BREAK
	case 18:
	YY_RULE_SETUP
	#line 51 "flexample.l"
	{return PRIVATE; }
		YY_BREAK
	case 19:
	YY_RULE_SETUP
	#line 52 "flexample.l"
	{return PROTECTED; }
		YY_BREAK
	case 20:
	YY_RULE_SETUP
	#line 53 "flexample.l"
	{return PUBLIC; }
		YY_BREAK
	case 21:
	YY_RULE_SETUP
	#line 54 "flexample.l"
	{return RETURN; }
		YY_BREAK
	case 22:
	YY_RULE_SETUP
	#line 55 "flexample.l"
	{return SELECT; }
		YY_BREAK
	case 23:
	YY_RULE_SETUP
	#line 56 "flexample.l"
	{return SUB; }
		YY_BREAK
	case 24:
	YY_RULE_SETUP
	#line 57 "flexample.l"
	{return THEN; }
		YY_BREAK
	case 25:
	YY_RULE_SETUP
	#line 58 "flexample.l"
	{return WHILE; }
		YY_BREAK
	case 26:
	YY_RULE_SETUP
	#line 59 "flexample.l"
	{return OR; }
		YY_BREAK
	case 27:
	YY_RULE_SETUP
	#line 60 "flexample.l"
	{return AND; }
		YY_BREAK
	case 28:
	YY_RULE_SETUP
	#line 61 "flexample.l"
	{return XOR; }
		YY_BREAK
	case 29:
	YY_RULE_SETUP
	#line 62 "flexample.l"
	{return NOT; }
		YY_BREAK
	case 30:
	YY_RULE_SETUP
	#line 63 "flexample.l"
	{return BYVAL; }
		YY_BREAK
	case 31:
	YY_RULE_SETUP
	#line 64 "flexample.l"
	{return LOOP; }
		YY_BREAK
	case 32:
	YY_RULE_SETUP
	#line 66 "flexample.l"
	{return LESS_OR_EQUAL; }
		YY_BREAK
	case 33:
	YY_RULE_SETUP
	#line 67 "flexample.l"
	{return MORE_OR_EQUAL; }
		YY_BREAK
	case 34:
	YY_RULE_SETUP
	#line 68 "flexample.l"
	{return NOT_EQUAL; }
		YY_BREAK
	case 35:
	YY_RULE_SETUP
	#line 69 "flexample.l"
	{return ASSIGN_CONSTRUCT; }
		YY_BREAK
	case 36:
	YY_RULE_SETUP
	#line 70 "flexample.l"
	{return ASSIGN_MULT; }
		YY_BREAK
	case 37:
	YY_RULE_SETUP
	#line 71 "flexample.l"
	{return ASSIGN_ORD_DIV; }
		YY_BREAK
	case 38:
	YY_RULE_SETUP
	#line 72 "flexample.l"
	{return ASSIGN_INT_DIV; }
		YY_BREAK
	case 39:
	YY_RULE_SETUP
	#line 73 "flexample.l"
	{return ASSIGN_ADD; }
		YY_BREAK
	case 40:
	YY_RULE_SETUP
	#line 74 "flexample.l"
	{return ASSIGN_SUB; }
		YY_BREAK
	case 41:
	YY_RULE_SETUP
	#line 75 "flexample.l"
	{return ASSIGN_LSHIFT; }
		YY_BREAK
	case 42:
	YY_RULE_SETUP
	#line 76 "flexample.l"
	{return ASSIGN_RSHIFT; }
		YY_BREAK
	case 43:
	YY_RULE_SETUP
	#line 77 "flexample.l"
	{return ASSIGN_CONCAT; }
		YY_BREAK
	case 44:
	YY_RULE_SETUP
	#line 78 "flexample.l"
	{ return '('; }
		YY_BREAK
	case 45:
	YY_RULE_SETUP
	#line 79 "flexample.l"
	{ return ')'; }
		YY_BREAK
	case 46:
	YY_RULE_SETUP
	#line 81 "flexample.l"
	{ return '{'; }
		YY_BREAK
	case 47:
	YY_RULE_SETUP
	#line 82 "flexample.l"
	{ return '}'; }
		YY_BREAK
	case 48:
	YY_RULE_SETUP
	#line 84 "flexample.l"
	{ return '+'; }
		YY_BREAK
	case 49:
	YY_RULE_SETUP
	#line 85 "flexample.l"
	{ return '-'; }
		YY_BREAK
	case 50:
	YY_RULE_SETUP
	#line 86 "flexample.l"
	{ return '*'; }
		YY_BREAK
	case 51:
	YY_RULE_SETUP
	#line 87 "flexample.l"
	{ return '/'; }
		YY_BREAK
	case 52:
	YY_RULE_SETUP
	#line 88 "flexample.l"
	{ return '='; }
		YY_BREAK
	case 53:
	YY_RULE_SETUP
	#line 89 "flexample.l"
	{ return '<'; }
		YY_BREAK
	case 54:
	YY_RULE_SETUP
	#line 90 "flexample.l"
	{ return '>'; }
		YY_BREAK
	case 55:
	YY_RULE_SETUP
	#line 91 "flexample.l"
	{ return '^'; }
		YY_BREAK
	case 56:
	YY_RULE_SETUP
	#line 92 "flexample.l"
	{ return '&'; }
		YY_BREAK
	case 57:
	YY_RULE_SETUP
	#line 94 "flexample.l"
	{ return ','; }
		YY_BREAK
	case 58:
	YY_RULE_SETUP
	#line 96 "flexample.l"
	{BEGIN(COMMENT); }
		YY_BREAK
	case 59:
	YY_RULE_SETUP
	#line 97 "flexample.l"

		YY_BREAK
	case 60:
		/* rule 60 can match eol */
		YY_RULE_SETUP
		#line 98 "flexample.l"
		{BEGIN(INITIAL); return END_OF_LINE; }
			YY_BREAK
		case YY_STATE_EOF(COMMENT):
		#line 99 "flexample.l"
		{BEGIN(INITIAL); }
			YY_BREAK
		case 61:
		YY_RULE_SETUP
		#line 101 "flexample.l"
		{BEGIN(DATETIME); }
			YY_BREAK
		case 62:
		YY_RULE_SETUP
		#line 102 "flexample.l"
		{ strcat(buf, yytext); }
			YY_BREAK
		case 63:
		YY_RULE_SETUP
		#line 103 "flexample.l"
		{BEGIN(INITIAL); yylval.str_val = (char*)malloc(strlen(buf) + 1); strcpy(yylval.datetime_val, buf); return DATETIME_VALUE; }
			YY_BREAK
		case 64:
		YY_RULE_SETUP
		#line 107 "flexample.l"
		{ buf[0] = 0; BEGIN(STRING_LITERAL); }
			YY_BREAK
		case 65:
			/* rule 65 can match eol */
			YY_RULE_SETUP
			#line 108 "flexample.l"
			{ strcat(buf, yytext); }
				YY_BREAK
			case 66:
			YY_RULE_SETUP
			#line 109 "flexample.l"
			{ strcat(buf, "\""); }
				YY_BREAK
			case YY_STATE_EOF(STRING_LITERAL):
			#line 110 "flexample.l"
			{  printf("\nError: unterminated string literal\n"); yyterminate(); }
				YY_BREAK
			case 67:
			YY_RULE_SETUP
			#line 111 "flexample.l"
			{  BEGIN(INITIAL); yylval.str_val = (char*)malloc(strlen(buf) + 1); strcpy(yylval.str_val, buf); return STRING_VALUE; }
				YY_BREAK
			case 68:
			YY_RULE_SETUP
			#line 113 "flexample.l"
			{remove_substr(yytext, "_"); yylval.int_val = atoi(yytext); return INT_VALUE; }
				YY_BREAK
			case 69:
			YY_RULE_SETUP
			#line 114 "flexample.l"
			{remove_substr(yytext, "_"); remove_substr(yytext, "&H");  result = HextoDeci(yytext); return INT_VALUE; }
				YY_BREAK
			case 70:
			YY_RULE_SETUP
			#line 115 "flexample.l"
			{remove_substr(yytext, "_"); remove_substr(yytext, "&B"); result = BintoDeci(yytext); return INT_VALUE; }
				YY_BREAK
			case 71:
			YY_RULE_SETUP
			#line 116 "flexample.l"
			{yylval.double_val = atof(yytext); return DOUBLE_VALUE; }
				YY_BREAK
			case 72:
				/* rule 72 can match eol */
				YY_RULE_SETUP
				#line 118 "flexample.l"
				{printf("\nString const: %s\n", yytext); }
					YY_BREAK
				case 73:
				YY_RULE_SETUP
				#line 122 "flexample.l"
				{yylval.bool_val = 1; return BOOLEAN_VALUE; }
					YY_BREAK
				case 74:
				YY_RULE_SETUP
				#line 123 "flexample.l"
				{yylval.bool_val = 0; return BOOLEAN_VALUE; }
					YY_BREAK
				case 75:
				YY_RULE_SETUP
				#line 125 "flexample.l"
				{yylval.id_var_name = (char*)malloc(strlen(yytext) + 1); strcpy(yylval.id_var_name, yytext); return IDENTIFIER; }
					YY_BREAK
				case 76:
					/* rule 76 can match eol */
					YY_RULE_SETUP
					#line 127 "flexample.l"
					{return END_OF_LINE; }
						YY_BREAK
					case YY_STATE_EOF(INITIAL):
					case YY_STATE_EOF(DATETIME):
					#line 129 "flexample.l"
					{ static int once = 0; return once++ ? 0 : END_OF_LINE; }
						YY_BREAK
					case 77:
					YY_RULE_SETUP
					#line 130 "flexample.l"
					ECHO;
						YY_BREAK
					#line 1337 "lex.yy.c"

						case YY_END_OF_BUFFER:
							{
							/* Amount of text matched not including the EOB char. */
							int yy_amount_of_matched_text = (int)(yy_cp - (yytext_ptr)) - 1;

							/* Undo the effects of YY_DO_BEFORE_ACTION. */
							*yy_cp = (yy_hold_char);
							YY_RESTORE_YY_MORE_OFFSET

							if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW)
								{
								/* We're scanning a new file or input source.  It's
								 * possible that this happened because the user
								 * just pointed yyin at a new source and called
								 * yylex().  If so, then we have to assure
								 * consistency between YY_CURRENT_BUFFER and our
								 * globals.  Here is the right place to do so, because
								 * this is the first action (other than possibly a
								 * back-up) that will match for the new input source.
								 */
								(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
								YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
								YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
								}

							/* Note that here we test for yy_c_buf_p "<=" to the position
							 * of the first EOB in the buffer, since yy_c_buf_p will
							 * already have been incremented past the NUL character
							 * (since all states make transitions on EOB to the
							 * end-of-buffer state).  Contrast this with the test
							 * in input().
							 */
							if ((yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)])
								{ /* This was really a NUL. */
								yy_state_type yy_next_state;

								(yy_c_buf_p) = (yytext_ptr)+yy_amount_of_matched_text;

								yy_current_state = yy_get_previous_state();

								/* Okay, we're now positioned to make the NUL
								 * transition.  We couldn't have
								 * yy_get_previous_state() go ahead and do it
								 * for us because it doesn't know how to deal
								 * with the possibility of jamming (and we don't
								 * want to build jamming into it because then it
								 * will run more slowly).
								 */

								yy_next_state = yy_try_NUL_trans(yy_current_state);

								yy_bp = (yytext_ptr)+YY_MORE_ADJ;

								if (yy_next_state)
									{
									/* Consume the NUL. */
									yy_cp = ++(yy_c_buf_p);
									yy_current_state = yy_next_state;
									goto yy_match;
									}

								else
									{
									yy_cp = (yy_c_buf_p);
									goto yy_find_action;
									}
								}

							else switch (yy_get_next_buffer())
								{
								case EOB_ACT_END_OF_FILE:
									{
									(yy_did_buffer_switch_on_eof) = 0;

									if (yywrap())
										{
										/* Note: because we've taken care in
										 * yy_get_next_buffer() to have set up
										 * yytext, we can now set up
										 * yy_c_buf_p so that if some total
										 * hoser (like flex itself) wants to
										 * call the scanner after we return the
										 * YY_NULL, it'll still work - another
										 * YY_NULL will get returned.
										 */
										(yy_c_buf_p) = (yytext_ptr)+YY_MORE_ADJ;

										yy_act = YY_STATE_EOF(YY_START);
										goto do_action;
										}

									else
										{
										if (!(yy_did_buffer_switch_on_eof))
											YY_NEW_FILE;
										}
									break;
									}

								case EOB_ACT_CONTINUE_SCAN:
									(yy_c_buf_p) =
										(yytext_ptr)+yy_amount_of_matched_text;

									yy_current_state = yy_get_previous_state();

									yy_cp = (yy_c_buf_p);
									yy_bp = (yytext_ptr)+YY_MORE_ADJ;
									goto yy_match;

								case EOB_ACT_LAST_MATCH:
									(yy_c_buf_p) =
									&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

									yy_current_state = yy_get_previous_state();

									yy_cp = (yy_c_buf_p);
									yy_bp = (yytext_ptr)+YY_MORE_ADJ;
									goto yy_find_action;
								}
							break;
							}

						default:
							YY_FATAL_ERROR(
								"fatal flex scanner internal error--no action found");
						} /* end of action switch */
							} /* end of scanning one token */
						} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
	static int yy_get_next_buffer(void)
{
	char* dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char* source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ((yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)+1])
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--end of buffer missed");

	if (YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0)
	{ /* Don't try to fill the buffer, so this is an EOF. */
		if ((yy_c_buf_p)-(yytext_ptr)-YY_MORE_ADJ == 1)
		{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
		}

		else
		{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
		}
	}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int)((yy_c_buf_p)-(yytext_ptr)-1);

	for (i = 0; i < number_to_move; ++i)
		*(dest++) = *(source++);

	if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING)
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
	{
		int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while (num_to_read <= 0)
		{ /* Not enough room in the buffer - grow it. */

		/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int)((yy_c_buf_p)-b->yy_ch_buf);

			if (b->yy_is_our_buffer)
			{
				int new_size = b->yy_buf_size * 2;

				if (new_size <= 0)
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char*)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void*)b->yy_ch_buf,
						(yy_size_t)(b->yy_buf_size + 2));
			}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if (!b->yy_ch_buf)
				YY_FATAL_ERROR(
					"fatal error - scanner input buffer overflow");

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
				number_to_move - 1;

		}

		if (num_to_read > YY_READ_BUF_SIZE)
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT((&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read);

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	if ((yy_n_chars) == 0)
	{
		if (number_to_move == YY_MORE_ADJ)
		{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin);
		}

		else
		{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
		}
	}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars)+number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars)+number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char*)yyrealloc(
			(void*)YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t)new_size);
		if (!YY_CURRENT_BUFFER_LVALUE->yy_ch_buf)
			YY_FATAL_ERROR("out of dynamic memory in yy_get_next_buffer()");
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int)(new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)+1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state(void)
{
	yy_state_type yy_current_state;
	char* yy_cp;

	yy_current_state = (yy_start);

	for (yy_cp = (yytext_ptr)+YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp)
	{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if (yy_accept[yy_current_state])
		{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}
		while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
		{
			yy_current_state = (int)yy_def[yy_current_state];
			if (yy_current_state >= 223)
				yy_c = yy_meta[yy_c];
		}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
static yy_state_type yy_try_NUL_trans(yy_state_type yy_current_state)
{
	int yy_is_jam;
	char* yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if (yy_accept[yy_current_state])
	{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
	}
	while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
	{
		yy_current_state = (int)yy_def[yy_current_state];
		if (yy_current_state >= 223)
			yy_c = yy_meta[yy_c];
	}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 222);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

static void yyunput(int c, char* yy_bp)
{
	char* yy_cp;

	yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if (yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2)
	{ /* need to shift things up to make room */
	/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars)+2;
		char* dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char* source =
			&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while (source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf)
			*--dest = *--source;

		yy_cp += (int)(dest - source);
		yy_bp += (int)(dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int)YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if (yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2)
			YY_FATAL_ERROR("flex scanner push-back overflow");
	}

	*--yy_cp = (char)c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput(void)
#else
static int input(void)
#endif

{
	int c;

	*(yy_c_buf_p) = (yy_hold_char);

	if (*(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR)
	{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ((yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)])
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
		{ /* need more input */
			int offset = (int)((yy_c_buf_p)-(yytext_ptr));
			++(yy_c_buf_p);

			switch (yy_get_next_buffer())
			{
			case EOB_ACT_LAST_MATCH:
				/* This happens because yy_g_n_b()
				 * sees that we've accumulated a
				 * token and flags that we need to
				 * try matching the token before
				 * proceeding.  But for input(),
				 * there's no matching to consider.
				 * So convert the EOB_ACT_LAST_MATCH
				 * to EOB_ACT_END_OF_FILE.
				 */

				 /* Reset buffer status. */
				yyrestart(yyin);

				/*FALLTHROUGH*/

			case EOB_ACT_END_OF_FILE:
			{
				if (yywrap())
					return 0;

				if (!(yy_did_buffer_switch_on_eof))
					YY_NEW_FILE;
#ifdef __cplusplus
				return yyinput();
#else
				return input();
#endif
			}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) = (yytext_ptr)+offset;
				break;
			}
		}
	}

	c = *(unsigned char*)(yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyrestart(FILE* input_file)
{

	if (!YY_CURRENT_BUFFER) {
		yyensure_buffer_stack();
		YY_CURRENT_BUFFER_LVALUE =
			yy_create_buffer(yyin, YY_BUF_SIZE);
	}

	yy_init_buffer(YY_CURRENT_BUFFER, input_file);
	yy_load_buffer_state();
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 *
 */
void yy_switch_to_buffer(YY_BUFFER_STATE  new_buffer)
{

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
	 */
	yyensure_buffer_stack();
	if (YY_CURRENT_BUFFER == new_buffer)
		return;

	if (YY_CURRENT_BUFFER)
	{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state(void)
{
	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
YY_BUFFER_STATE yy_create_buffer(FILE* file, int  size)
{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE)yyalloc(sizeof(struct yy_buffer_state));
	if (!b)
		YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char*)yyalloc((yy_size_t)(b->yy_buf_size + 2));
	if (!b->yy_ch_buf)
		YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b, file);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 *
 */
void yy_delete_buffer(YY_BUFFER_STATE  b)
{

	if (!b)
		return;

	if (b == YY_CURRENT_BUFFER) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE)0;

	if (b->yy_is_our_buffer)
		yyfree((void*)b->yy_ch_buf);

	yyfree((void*)b);
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
static void yy_init_buffer(YY_BUFFER_STATE  b, FILE* file)

{
	int oerrno = errno;

	yy_flush_buffer(b);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	/* If b is the current buffer, then yy_init_buffer was _probably_
	 * called from yyrestart() or through yy_get_next_buffer.
	 * In that case, we don't want to reset the lineno or column.
	 */
	if (b != YY_CURRENT_BUFFER) {
		b->yy_bs_lineno = 1;
		b->yy_bs_column = 0;
	}

	b->yy_is_interactive = file ? (isatty(fileno(file)) > 0) : 0;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
void yy_flush_buffer(YY_BUFFER_STATE  b)
{
	if (!b)
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if (b == YY_CURRENT_BUFFER)
		yy_load_buffer_state();
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *
 */
void yypush_buffer_state(YY_BUFFER_STATE new_buffer)
{
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if (YY_CURRENT_BUFFER)
	{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state();
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *
 */
void yypop_buffer_state(void)
{
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state();
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;

	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
		 */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
		(num_to_alloc * sizeof(struct yy_buffer_state*)
		);
		if (!(yy_buffer_stack))
			YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1) {

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max)+grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
		((yy_buffer_stack),
			num_to_alloc * sizeof(struct yy_buffer_state*)
		);
		if (!(yy_buffer_stack))
			YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

		/* zero only the new slots.*/
		memset((yy_buffer_stack)+(yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer(char* base, yy_size_t  size)
{
	YY_BUFFER_STATE b;

	if (size < 2 ||
		base[size - 2] != YY_END_OF_BUFFER_CHAR ||
		base[size - 1] != YY_END_OF_BUFFER_CHAR)
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE)yyalloc(sizeof(struct yy_buffer_state));
	if (!b)
		YY_FATAL_ERROR("out of dynamic memory in yy_scan_buffer()");

	b->yy_buf_size = (int)(size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b);

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 *
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string(const char* yystr)
{

	return yy_scan_bytes(yystr, (int)strlen(yystr));
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes(const char* yybytes, int  _yybytes_len)
{
	YY_BUFFER_STATE b;
	char* buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t)(_yybytes_len + 2);
	buf = (char*)yyalloc(n);
	if (!buf)
		YY_FATAL_ERROR("out of dynamic memory in yy_scan_bytes()");

	for (i = 0; i < _yybytes_len; ++i)
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len + 1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf, n);
	if (!b)
		YY_FATAL_ERROR("bad buffer in yy_scan_bytes()");

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error(const char* msg)
{
	fprintf(stderr, "%s\n", msg);
	exit(YY_EXIT_FAILURE);
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 *
 */
int yyget_lineno(void)
{

	return yylineno;
}

/** Get the input stream.
 *
 */
FILE* yyget_in(void)
{
	return yyin;
}

/** Get the output stream.
 *
 */
FILE* yyget_out(void)
{
	return yyout;
}

/** Get the length of the current token.
 *
 */
int yyget_leng(void)
{
	return yyleng;
}

/** Get the current token.
 *
 */

char* yyget_text(void)
{
	return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 *
 */
void yyset_lineno(int  _line_number)
{

	yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 *
 * @see yy_switch_to_buffer
 */
void yyset_in(FILE* _in_str)
{
	yyin = _in_str;
}

void yyset_out(FILE* _out_str)
{
	yyout = _out_str;
}

int yyget_debug(void)
{
	return yy_flex_debug;
}

void yyset_debug(int  _bdebug)
{
	yy_flex_debug = _bdebug;
}

static int yy_init_globals(void)
{
	/* Initialization is the same as for the non-reentrant scanner.
 * This function is called from yylex_destroy(), so don't allocate here.
 */

	(yy_buffer_stack) = NULL;
	(yy_buffer_stack_top) = 0;
	(yy_buffer_stack_max) = 0;
	(yy_c_buf_p) = NULL;
	(yy_init) = 0;
	(yy_start) = 0;

	/* Defined in main.c */
#ifdef YY_STDINIT
	yyin = stdin;
	yyout = stdout;
#else
	yyin = NULL;
	yyout = NULL;
#endif

	/* For future reference: Set errno on error, since we are called by
	 * yylex_init()
	 */
	return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy(void)
{

	/* Pop the buffer stack, destroying each element. */
	while (YY_CURRENT_BUFFER) {
		yy_delete_buffer(YY_CURRENT_BUFFER);
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack));
	(yy_buffer_stack) = NULL;

	/* Reset the globals. This is important in a non-reentrant scanner so the next time
	 * yylex() is called, initialization will occur. */
	yy_init_globals();

	return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy(char* s1, const char* s2, int n)
{

	int i;
	for (i = 0; i < n; ++i)
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(const char* s)
{
	int n;
	for (n = 0; s[n]; ++n)
		;

	return n;
}
#endif

void* yyalloc(yy_size_t  size)
{
	return malloc(size);
}

void* yyrealloc(void* ptr, yy_size_t  size)
{

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree(void* ptr)
{
	free((char*)ptr);	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 130 "flexample.l"


int val(char c)
{
	if (c >= '0' && c <= '9')
		return (int)c - '0';
	else
		return (int)c - 'A' + 10;
}

int BintoDeci(char* str)
{
	short i;
	int res = 0;

	for (i = 0; i < sizeof(long) * 8 && str[i]; ++i)
	{
		res <<= 1;
		res |= (str[i] - '0');
	}
	return res;
}

int HextoDeci(char* str)
{
	int len = strlen(str);
	int power = 1;
	int num = 0;
	int i;


	for (i = len - 1; i >= 0; i--)
	{


		if (val(str[i]) >= 16)
		{
			printf("Invalid Number");
			return -1;
		}

		num += val(str[i]) * power;
		power = power * 16;
	}

	return num;
}


void remove_substr(char* str, const char* substr)
{
	char* begin = str;
	char* end = str;
	char* cur;
	const char* sub;

	while (*end)
	{
		for (sub = substr, cur = end; *sub && *cur && *sub == *cur; ++cur, ++sub);

		if (*sub == 0)
		{
			end = cur;
		}

		if (begin != end)
		{
			*begin = *end;
		}

		if (*sub != 0)
		{
			begin++;
			end++;
		}
	}
	*begin = 0;



}

// void main(int argc, char** argv){
//     yyin = fopen(argv[1], "r");
//     yylex();
//     return;
// }

